version: '3.5'

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-osu-server}
    volumes:
      - /var/lib/postgresql/osu-api-server:/var/lib/postgresql/data

  backend:
    image: deissh/osu-api-server:${BACKEND_TAG:-latest}
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - postgres