debug: true

# External services
services:
  avatars: 'https://a.localhost'
  cheesegull: 'https://storage.localhost'


# API server configuration
server:
  host: ${SERVER__HOST|127.0.0.1}
  port: ${SERVER__PORT|2100}
  cors:
    enable: false
    allow_origins:
      - localhost
    allow_headers:
      - Origin
      - Content-Type
      - Accept

  sentry_dsn: ${SERVER__SENTRY_DSN}

  database:
    driver: ${SERVER__DATABASE__DRIVER|postgres}
    dsn: ${SERVER__DATABASE__DSN|postgres://postgres:postgres@/osuserver}

  redis:
    host: ${SERVER__REDIS__HOST|127.0.0.1:6379}
    password: ${SERVER__REDIS__PASSWORD|}
    db: ${SERVER__REDIS__DB}

  mailgun:
    domain: ''
    private_key: ''
    public_key: ''
    from: ''
