debug: true

# External services
services:
  avatars: 'https://a.localhost'
  cheesegull: 'https://storage.localhost'


# API server configuration
server:
  host: '127.0.0.1'
  port: 2100
  http_log_format: '{"level": "info","time":${time_unix},"id":"${id}","remote_ip":"${remote_ip}","host":"${host}","method":"${method}","uri":"${uri}","status":${status},"error":"${error}","latency":${latency},"latency_human":"${latency_human}","bytes_in":${bytes_in},`"bytes_out":${bytes_out}}\n'
  cors:
    enable: true
    allow_origins:
      - localhost
    allow_headers:
      - Origin
      - Content-Type
      - Accept

  sentry_dns:

  database:
    driver: mysql
    dsn: 'root:toor@/osuserver'

  redis:
    host: '127.0.0.1:6379'
    password: ''
    db: 0

  mailgun:
    domain: ''
    private_key: ''
    public_key: ''
    from: ''