# API server configuration
host: 127.0.0.1
port: 2400

database:
  driver: postgres
  dsn: postgres://postgres:postgres@/osuserver?sslmode=disable


# Slave database configuration
mirror:
  bancho:
    access_token: token
    refresh_token: token

  s3:
    secret_id: 123
    secret_key: 321
    bucket: beatmaps
