# API server configuration
host: 127.0.0.1
port: 2400

database:
  driver: postgres
  dsn: postgres://postgres:postgres@/osuserver?sslmode=disable


# Slave database configuration
mirror:
  bancho:
    using_refresh_token: true

    # using by oauth
    # public information
    client_id: 5
    client_secret: 'FGc9GAtyHzeQDshWP5Ah7dega8hJACAJpQtw6OXk'

    username: test
    password: tset

  s3:
    secret_id: 123
    secret_key: 321
    bucket: beatmaps
