name: Go
on: [pull_request]
jobs:
  test:
    name: Unit test
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: ./scripts/install.sh

    - name: Lint
      run: ./scripts/lint.sh

    - name: Build
      run: go build cmd/www/main.go
    
    - name: Test
      timeout-minutes: 10
      run: go test ./...
