name: Create Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
        id: go

      - name: Setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-latest-go-

      - name: Get dependencies
        run: make install

      - name: Lint
        run: make lint

    unit-test:
      name: Unit test
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go 1.13
          uses: actions/setup-go@v1
          with:
            go-version: 1.13.x
          id: go

        - name: Setup env
          run: |
            echo "::set-env name=GOPATH::$(go env GOPATH)"
            echo "::add-path::$(go env GOPATH)/bin"
          shell: bash

        - name: Check out code into the Go module directory
          uses: actions/checkout@v1

        - uses: actions/cache@v1
          with:
            path: ~/go/pkg/mod
            key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ubuntu-latest-go-

        - name: Get dependencies
          run: make install

        - name: Run tests
          timeout-minutes: 10
          run: make test

    build:
      name: Build cmds
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go 1.13
          uses: actions/setup-go@v1
          with:
            go-version: 1.13.x
          id: go

        - name: Setup env
          run: |
            echo "::set-env name=GOPATH::$(go env GOPATH)"
            echo "::add-path::$(go env GOPATH)/bin"
          shell: bash

        - name: Check out code into the Go module directory
          uses: actions/checkout@v1

        - uses: actions/cache@v1
          with:
            path: ~/go/pkg/mod
            key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ubuntu-latest-go-

        - name: Get dependencies
          run: make install

        - name: Build
          run: make build

        - name: Run tests
          timeout-minutes: 10
          run: make test